### ISSUE TITLE
Missing Endpoint does not result in errored event or retry

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-consent-bridge#61]
[ERROR] 12:20:42.305 [nats:16] nl.nuts.consent.bridge.pipelines.NatsToCordaPipeline - Not all given organizations have a consent endpoint in the registry
java.lang.IllegalArgumentException: Not all given organizations have a consent endpoint in the registry
	at nl.nuts.consent.bridge.corda.CordaService.createConsentBranch(CordaService.kt:355) ~[classes!/:?]
	at nl.nuts.consent.bridge.pipelines.NatsToCordaPipeline.processEventConsentRequestConstructed(NatsToCordaPipeline.kt:223) ~[classes!/:?]
	at nl.nuts.consent.bridge.pipelines.NatsToCordaPipeline.processEvent(NatsToCordaPipeline.kt:188) ~[classes!/:?]
	at nl.nuts.consent.bridge.pipelines.NatsToCordaPipeline$startListeners$1.onMessage(NatsToCordaPipeline.kt:126) ~[classes!/:?]
	at io.nats.streaming.StreamingConnectionImpl.processMsg(StreamingConnectionImpl.java:932) ~[java-nats-streaming-2.2.3.jar!/:2.2.3]
	at io.nats.streaming.StreamingConnectionImpl.lambda$getDispatcherByName$4(StreamingConnectionImpl.java:527) ~[java-nats-streaming-2.2.3.jar!/:2.2.3]
	at io.nats.client.impl.NatsDispatcher.run(NatsDispatcher.java:98) ~[jnats-2.6.7.jar!/:2.6.7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by woutslakhorst** [comment]
same goes for other illegalArgumentExceptions..

**Comment by woutslakhorst** [comment]
they are handled correctly but status and error message are not updated!
